# default false
release_mode = false


[app]
name = "Read Follow"
port = ":8080"
host = "47.92.130.14"

[database]
type = "postgres"
dbname = "spider"
user = "postgres"
password  = "123456"
host = "localhost"
port = "5432"


[wechat]
appid = "wx702b93aef72f3549"
appsecret = "8b69f45fc737a938cbaaffc05b192394"
oriid  = "gh_cb5c31e2c2dd"
token  = "admin"
aeskey= ""
